// <auto-generated />
using System;
using Game_On.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game_On.Migrations
{
    [DbContext(typeof(ModelContext))]
    [Migration("20251129025241_Classement")]
    partial class Classement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Game_On.Models.ClassementDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateClassement")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DepartementId")
                        .HasColumnType("int");

                    b.Property<int?>("EntrepriseId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartementId");

                    b.HasIndex("EntrepriseId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("ClassementDate");
                });

            modelBuilder.Entity("Game_On.Models.Departement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("int");

                    b.Property<string>("NomDepartement")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Departement");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntrepriseId = 1,
                            NomDepartement = "Gestionnaires de projet"
                        },
                        new
                        {
                            Id = 2,
                            EntrepriseId = 1,
                            NomDepartement = "Analystes d'affaires"
                        },
                        new
                        {
                            Id = 3,
                            EntrepriseId = 1,
                            NomDepartement = "Analystes d'applications"
                        },
                        new
                        {
                            Id = 4,
                            EntrepriseId = 1,
                            NomDepartement = "Développeurs"
                        },
                        new
                        {
                            Id = 5,
                            EntrepriseId = 1,
                            NomDepartement = "Spécialistes en assurance qualité"
                        },
                        new
                        {
                            Id = 6,
                            EntrepriseId = 2,
                            NomDepartement = "Technologies"
                        },
                        new
                        {
                            Id = 7,
                            EntrepriseId = 2,
                            NomDepartement = "Services bancaires"
                        },
                        new
                        {
                            Id = 8,
                            EntrepriseId = 3,
                            NomDepartement = "Informatique"
                        },
                        new
                        {
                            Id = 9,
                            EntrepriseId = 3,
                            NomDepartement = "Ingénierie"
                        },
                        new
                        {
                            Id = 10,
                            EntrepriseId = 4,
                            NomDepartement = "Développement"
                        },
                        new
                        {
                            Id = 11,
                            EntrepriseId = 4,
                            NomDepartement = "Support technique"
                        },
                        new
                        {
                            Id = 12,
                            EntrepriseId = 5,
                            NomDepartement = "Consultation"
                        },
                        new
                        {
                            Id = 13,
                            EntrepriseId = 5,
                            NomDepartement = "Infrastructure"
                        },
                        new
                        {
                            Id = 14,
                            EntrepriseId = 6,
                            NomDepartement = "Systèmes d'information"
                        },
                        new
                        {
                            Id = 15,
                            EntrepriseId = 6,
                            NomDepartement = "Commerce électronique"
                        });
                });

            modelBuilder.Entity("Game_On.Models.Entreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomDomaine")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomEntreprise")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Entreprise");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomDomaine = "cchic.ca",
                            NomEntreprise = "Hourglass Unlimited",
                            Score = 0
                        },
                        new
                        {
                            Id = 2,
                            NomDomaine = "cius.ca",
                            NomEntreprise = "Centre des urgences",
                            Score = 0
                        });
                });

            modelBuilder.Entity("Game_On.Models.Gagnant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Gagnant");
                });

            modelBuilder.Entity("Game_On.Models.GameCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomGameCategory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GameCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomGameCategory = "Puzzle"
                        },
                        new
                        {
                            Id = 2,
                            NomGameCategory = "Logique"
                        });
                });

            modelBuilder.Entity("Game_On.Models.Jeu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstDisponible")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("GameCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("NomJeu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Jeu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstDisponible = true,
                            GameCategoryId = 1,
                            NomJeu = "Sudoku Master"
                        },
                        new
                        {
                            Id = 2,
                            EstDisponible = false,
                            GameCategoryId = 2,
                            NomJeu = "Poker Pro"
                        },
                        new
                        {
                            Id = 3,
                            EstDisponible = false,
                            GameCategoryId = 2,
                            NomJeu = "Quiz Mania"
                        });
                });

            modelBuilder.Entity("Game_On.Models.Partie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Save")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SudokuId")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Partie");
                });

            modelBuilder.Entity("Game_On.Models.Sudoku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Difficulte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsTraining")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Puzzle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Sudoku");
                });

            modelBuilder.Entity("Game_On.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartementId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LogoutTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrenomUtilisateur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TempsDeJeuCumule")
                        .HasColumnType("time(6)");

                    b.HasKey("Id");

                    b.HasIndex("DepartementId");

                    b.HasIndex("EntrepriseId");

                    b.ToTable("Utilisateur");
                });

            modelBuilder.Entity("Game_On.Models.ClassementDate", b =>
                {
                    b.HasOne("Game_On.Models.Departement", "Departement")
                        .WithMany()
                        .HasForeignKey("DepartementId");

                    b.HasOne("Game_On.Models.Entreprise", "Entreprise")
                        .WithMany()
                        .HasForeignKey("EntrepriseId");

                    b.HasOne("Game_On.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departement");

                    b.Navigation("Entreprise");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Game_On.Models.Utilisateur", b =>
                {
                    b.HasOne("Game_On.Models.Departement", "Departement")
                        .WithMany()
                        .HasForeignKey("DepartementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game_On.Models.Entreprise", "Entreprise")
                        .WithMany()
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departement");

                    b.Navigation("Entreprise");
                });
#pragma warning restore 612, 618
        }
    }
}
