// <auto-generated />
using System;
using Game_On.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game_On.Migrations
{
    [DbContext(typeof(ModelContext))]
    [Migration("20251029213708_ModificationTableUtilisateur")]
    partial class ModificationTableUtilisateur
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Game_On.Models.Departement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("int");

                    b.Property<string>("NomDepartement")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Departement");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntrepriseId = 1,
                            NomDepartement = "Gestionnaires de projet"
                        },
                        new
                        {
                            Id = 2,
                            EntrepriseId = 1,
                            NomDepartement = "Analystes d'affaires"
                        },
                        new
                        {
                            Id = 3,
                            EntrepriseId = 1,
                            NomDepartement = "Analystes d'applications"
                        },
                        new
                        {
                            Id = 4,
                            EntrepriseId = 1,
                            NomDepartement = "Développeurs"
                        },
                        new
                        {
                            Id = 5,
                            EntrepriseId = 1,
                            NomDepartement = "Spécialistes en assurance qualité"
                        },
                        new
                        {
                            Id = 6,
                            EntrepriseId = 2,
                            NomDepartement = "Technologies"
                        },
                        new
                        {
                            Id = 7,
                            EntrepriseId = 2,
                            NomDepartement = "Services bancaires"
                        },
                        new
                        {
                            Id = 8,
                            EntrepriseId = 3,
                            NomDepartement = "Informatique"
                        },
                        new
                        {
                            Id = 9,
                            EntrepriseId = 3,
                            NomDepartement = "Ingénierie"
                        },
                        new
                        {
                            Id = 10,
                            EntrepriseId = 4,
                            NomDepartement = "Développement"
                        },
                        new
                        {
                            Id = 11,
                            EntrepriseId = 4,
                            NomDepartement = "Support technique"
                        },
                        new
                        {
                            Id = 12,
                            EntrepriseId = 5,
                            NomDepartement = "Consultation"
                        },
                        new
                        {
                            Id = 13,
                            EntrepriseId = 5,
                            NomDepartement = "Infrastructure"
                        },
                        new
                        {
                            Id = 14,
                            EntrepriseId = 6,
                            NomDepartement = "Systèmes d'information"
                        },
                        new
                        {
                            Id = 15,
                            EntrepriseId = 6,
                            NomDepartement = "Commerce électronique"
                        });
                });

            modelBuilder.Entity("Game_On.Models.Entreprise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomEntreprise")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Entreprise");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomEntreprise = "Hourglass Unlimited"
                        },
                        new
                        {
                            Id = 2,
                            NomEntreprise = "Desjardins"
                        },
                        new
                        {
                            Id = 3,
                            NomEntreprise = "Hydro-Québec"
                        },
                        new
                        {
                            Id = 4,
                            NomEntreprise = "Videotron"
                        },
                        new
                        {
                            Id = 5,
                            NomEntreprise = "CGI"
                        },
                        new
                        {
                            Id = 6,
                            NomEntreprise = "SAQ"
                        });
                });

            modelBuilder.Entity("Game_On.Models.Gagnant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Gagnant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Score = 48,
                            UtilisateurId = 13
                        },
                        new
                        {
                            Id = 2,
                            Score = 46,
                            UtilisateurId = 18
                        },
                        new
                        {
                            Id = 3,
                            Score = 45,
                            UtilisateurId = 14
                        });
                });

            modelBuilder.Entity("Game_On.Models.GameCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomGameCategory")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GameCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomGameCategory = "Puzzle"
                        },
                        new
                        {
                            Id = 2,
                            NomGameCategory = "Logique"
                        });
                });

            modelBuilder.Entity("Game_On.Models.Jeu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GameCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("NomJeu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Jeu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameCategoryId = 1,
                            NomJeu = "Sudoku"
                        });
                });

            modelBuilder.Entity("Game_On.Models.Partie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SudokuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Partie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateDebut = new DateTime(2025, 10, 28, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2025, 10, 28, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            SudokuId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateDebut = new DateTime(2025, 10, 28, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2025, 10, 28, 10, 48, 0, 0, DateTimeKind.Unspecified),
                            SudokuId = 1
                        },
                        new
                        {
                            Id = 3,
                            DateDebut = new DateTime(2025, 10, 28, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2025, 10, 28, 14, 22, 0, 0, DateTimeKind.Unspecified),
                            SudokuId = 1
                        },
                        new
                        {
                            Id = 4,
                            DateDebut = new DateTime(2025, 10, 28, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2025, 10, 28, 9, 5, 0, 0, DateTimeKind.Unspecified),
                            SudokuId = 2
                        },
                        new
                        {
                            Id = 5,
                            DateDebut = new DateTime(2025, 10, 28, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2025, 10, 28, 11, 42, 0, 0, DateTimeKind.Unspecified),
                            SudokuId = 2
                        },
                        new
                        {
                            Id = 6,
                            DateDebut = new DateTime(2025, 10, 28, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2025, 10, 28, 14, 8, 0, 0, DateTimeKind.Unspecified),
                            SudokuId = 2
                        },
                        new
                        {
                            Id = 7,
                            DateDebut = new DateTime(2025, 10, 28, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2025, 10, 28, 9, 58, 0, 0, DateTimeKind.Unspecified),
                            SudokuId = 3
                        },
                        new
                        {
                            Id = 8,
                            DateDebut = new DateTime(2025, 10, 28, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2025, 10, 28, 14, 5, 0, 0, DateTimeKind.Unspecified),
                            SudokuId = 3
                        },
                        new
                        {
                            Id = 9,
                            DateDebut = new DateTime(2025, 10, 28, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFin = new DateTime(2025, 10, 28, 17, 12, 0, 0, DateTimeKind.Unspecified),
                            SudokuId = 3
                        });
                });

            modelBuilder.Entity("Game_On.Models.Sudoku", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Difficulte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Puzzle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Sudoku");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulte = "Easy",
                            Puzzle = "302718690008060003000503018000091000460005980003607002000000870000936521905072030",
                            Solution = "352718694148269753679543218827491365461325987593687142236154879784936521915872436"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulte = "Medium",
                            Puzzle = "007300900030014070000020000078160059005800047002700160750093000280000000001400000",
                            Solution = "527386914836914572149527836478162359615839247392745168754293681283671495961458723"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Difficulte = "Hard",
                            Puzzle = "000040000610030402280610900100007030000200800030000000000950040005300007900001000",
                            Solution = "359742681617839452284615973198567234476293815532184769721958346845326197963471528"
                        });
                });

            modelBuilder.Entity("Game_On.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartementId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EntrepriseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("LogoutTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomUtilisateur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrenomUtilisateur")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartementId");

                    b.HasIndex("EntrepriseId");

                    b.ToTable("Utilisateur");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartementId = 1,
                            Email = "jean.tremblay@example.com",
                            EntrepriseId = 1,
                            LoginTime = new DateTime(2025, 10, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            LogoutTime = new DateTime(2025, 10, 28, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            MotDePasse = "Test@1234",
                            NomUtilisateur = "Tremblay",
                            PrenomUtilisateur = "Jean",
                            Pseudo = "jtremblay",
                            Score = 24
                        },
                        new
                        {
                            Id = 2,
                            DepartementId = 1,
                            Email = "marie.gagnon@example.com",
                            EntrepriseId = 1,
                            LoginTime = new DateTime(2025, 10, 28, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            LogoutTime = new DateTime(2025, 10, 28, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            MotDePasse = "Test@1234",
                            NomUtilisateur = "Gagnon",
                            PrenomUtilisateur = "Marie",
                            Pseudo = "mgagnon",
                            Score = 18
                        },
                        new
                        {
                            Id = 3,
                            DepartementId = 1,
                            Email = "pierre.roy@example.com",
                            EntrepriseId = 1,
                            LoginTime = new DateTime(2025, 10, 28, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            LogoutTime = new DateTime(2025, 10, 28, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            MotDePasse = "Test@1234",
                            NomUtilisateur = "Roy",
                            PrenomUtilisateur = "Pierre",
                            Pseudo = "proy",
                            Score = 15
                        });
                });

            modelBuilder.Entity("Game_On.Models.Utilisateur", b =>
                {
                    b.HasOne("Game_On.Models.Departement", "Departement")
                        .WithMany()
                        .HasForeignKey("DepartementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game_On.Models.Entreprise", "Entreprise")
                        .WithMany()
                        .HasForeignKey("EntrepriseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departement");

                    b.Navigation("Entreprise");
                });
#pragma warning restore 612, 618
        }
    }
}
